version: '3'

services:
    web:
        build: .
       
        ports:
            - "5000:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    ourdb:
        image: mongo:latest